linters:
  enable:
    - gosec        # Проверяет безопасность кода
    - govet        # Стандартный линтер Go
    - errcheck     # Проверяет обработку ошибок
    - staticcheck  # Продвинутый статический анализатор
    - gosimple     # Упрощение кода
    - ineffassign  # Проверяет неиспользуемые присваивания
    - unused       # Проверяет неиспользуемый код
    - gocyclo      # Проверяет цикломатическую сложность
    - misspell     # Проверяет опечатки в комментариях
    - bodyclose    # Проверяет закрытие HTTP response body
    - gocritic     # Дополнительные проверки стиля и возможных ошибок
    - revive       # Замена golint с дополнительными правилами
    - prealloc     # Предлагает предварительное выделение slice
    - unconvert    # Находит ненужные преобразования типов
    - gofmt        # Проверяет форматирование
    - goimports    # Проверяет импорты

run:
  deadline: 5m

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false