linters:
  enable:
    - gosec        # Checks code security
    - govet        # Standard Go linter
    - errcheck     # Checks error handling
    - staticcheck  # Advanced static analyzer
    - gosimple     # Code simplification
    - ineffassign  # Checks unused assignments
    - unused       # Checks unused code
    - gocyclo      # Checks cyclomatic complexity
    - misspell     # Checks spelling in comments
    - bodyclose    # Checks HTTP response body closure
    - gocritic     # Additional style checks and possible errors
    - revive       # Golint replacement with additional rules
    - prealloc     # Suggests slice preallocation
    - unconvert    # Finds unnecessary type conversions
    - gofmt        # Checks formatting
    - goimports    # Checks imports

run:
  deadline: 5m

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false