# Version for this file.
version: 1

# (Optional) List of env variables used during compilation.
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

# (Optional) Flags for the compiler.
flags:
  - -trimpath
  - -tags=netgo

# The OS to compile for. `GOOS` env variable will be set to this value.
goos: linux

# The architecture to compile for. `GOARCH` env variable will be set to this value.
goarch: amd64

# Binary output name.
binary: notification-relay-linux-amd64

# Version information through ldflags
ldflags:
  - "-s"  # Strip debug information
  - "-w"  # Strip DWARF symbol table
  - "-X main.Version={{ .Env.VERSION }}"
  - "-X main.BuildTime={{ .Env.BUILD_TIME }}"
  - "-X main.GitCommit={{ .Env.GIT_COMMIT }}"