version: '3.8'

services:
  notification-relay:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config:/etc/notification-relay
    environment:
      - NOTIFICATION_RELAY_CONFIG=/etc/notification-relay/config.json
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/notification-relay/service-account.json
      - LISTEN_PORT=5000
      - TRUSTED_PROXIES=127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    restart: unless-stopped

networks:
  notification-net:
    driver: bridge