services:
  notification-relay:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - LISTEN_PORT=${PORT:-5000}
      - GIN_MODE=release
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/notification-relay/service-account.json
    volumes:
      - ${CONFIG_DIR:-~/.notification-relay}:/etc/notification-relay
      - ${LOG_DIR:-~/.notification-relay/logs}:/var/log/notification-relay
    restart: unless-stopped
    networks:
      - notification-net

networks:
  notification-net:
    driver: bridge