name: Go Build

on:
  push:
    branches:
      - go
  pull_request:
    branches:
      - go

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o notification-relay-linux-amd64

      - name: Archive binary
        run: tar czf notification-relay-linux-amd64.tar.gz notification-relay-linux-amd64