name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o notification-relay-linux-amd64
          tar czf notification-relay-linux-amd64.tar.gz notification-relay-linux-amd64
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            notification-relay-linux-amd64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
          body: |
            Push Notification Relay Server ${{ github.ref_name }}
            
            ## Installation
            ```bash
            wget https://github.com/metalmon/relay-server/releases/download/${{ github.ref_name }}/notification-relay-linux-amd64.tar.gz
            tar xzf notification-relay-linux-amd64.tar.gz
            sudo mv notification-relay-linux-amd64 /usr/local/bin/notification-relay
            ```
            
            For complete installation instructions, see the [README](https://github.com/metalmon/relay-server#quick-installation-ubuntu) 